name: Generate Build Size

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - check-build
  pull_request:
    branches:
      - check-build

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell      # Checkout the Repo
    - uses: actions/checkout@v2

    # Install Node 12
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12
    
    - run: git rebase master
    - run: npm ci
    - run: npm run build
    